### ISSUE TITLE
Creating our own exclusion list for textlint-rule-spelling EN

### ISSUE THREAD

**Issue by donganzh** [textlint/textlint#603] opened 2019-05-21 13:50 UTC
@takahashim @azu @nodaguti Hi! In the .textlintrc file, how do we configure the skip pattern item so that it will exclude multiple words instead of just one? Is that the correct way to add an exclusion words list for this spelling check tool? Thanks!

**Comment by azu** [comment] 2019-05-21 14:43
This is textlint-rule-spelling's issue, is not textlint issue.

Duplicate of https://github.com/ta2gch/textlint-rule-spelling/issues/1

**Closed by azu** 2019-05-21 14:43 UTC
Labels: Type: Question
